const songs = [
  {
    id: 1,
    name: "Sadda Haq",
    artist: "Mohit Chauhan",
    image: "./songs_image/sadda_haq.jpg",
    genre: "Rock",
    source: "./songs_source/sadda_haq.mp3",
  },
  {
    id: 2,
    name: "Jo Bhi Main",
    artist: "Mohit Chauhan",
    image: "./songs_image/jo_bhi_main.jpg",
    genre: "Pop",
    source: "./songs_source/jo_bhi_main.mp3",
  },
  {
    id: 3,
    name: "Humsafar",
    artist: "Akhil Sachdeva",
    image: "./songs_image/Humsafar.jpg",
    genre: "Country",
    source: "./songs_source/humsafar.mp3",
  },
  {
    id: 4,
    name: "Ghungroo",
    artist: "Arijit Singh",
    image: "./songs_image/Ghungroo.jpg",
    genre: "Country",
    source: "./songs_source/Ghungroo.mp3",
  },
  {
    id: 5,
    name: "Bekhayali",
    artist: "Sachet Tandon",
    image: "./songs_image/Bekhayali.jpg",
    genre: "Classical",
    source: "./songs_source/Bekhayali.mp3",
  },
  {
    id: 6,
    name: "Nashe Si Chadh Gayi",
    artist: "Arijit Singh",
    image: "./songs_image/Nashe_Si_Chadh_Gayi.jpg",
    genre: "Country",
    source: "./songs_source/Nashe_Si_Chadh_Gayi.mp3",
  },
  {
    id: 7,
    name: "Galliyan",
    artist: "Ankit Tiwari",
    image: "./songs_image/Galliyan.jpg",
    genre: "Jazz",
    source: "./songs_source/Galliyan.mp3",
  },
  {
    id: 8,
    name: "Sun Raha Hai Na Tu",
    artist: "ANKIT TIWARI",
    image: "./songs_image/Sun_Raha_Hai_Na_Tu.jpg",
    genre: "Country",
    source: "./songs_source/Sun_Raha_Hai_Na_Tu.mp3",
  },
  {
    id: 9,
    name: "Tauba Tauba",
    artist: "Karan Aujla",
    image: "./songs_image/taubatauba.jpg",
    genre: "Rock",
    source: "./songs_source/Tauba_Tauba.mp3",
  },
  {
    id: 10,
    name: "Apna Bana Le",
    artist: "Arijit Singh",
    image: "./songs_image/Apna_Bana_Le.jpg",
    genre: "Classical",
    source: "./songs_source/Apna_Bana_Le.mp3",
  },
  {
    id: 11,
    name: "Bhool Bhulaiyaa 3",
    artist: "Arijit Singh",
    image: "./songs_image/Bhool_Bhulaiyaa_3.jpg",
    genre: "Hip-Hop",
    source: "./songs_source/bhool_bhuliya_3.mp3",
  },
];

export default songs;
